version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-stetepfunction-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j0p5l5p1f4w1"
s3_prefix = "sam-stetepfunction-example"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["StockBuyerFunction=941261018719.dkr.ecr.us-east-1.amazonaws.com/samstetepfunctionexample6e3f1fd1/stockbuyerfunctionda8aa733repo", "StockCheckerFunction=941261018719.dkr.ecr.us-east-1.amazonaws.com/samstetepfunctionexample6e3f1fd1/stockcheckerfunctionc185be2frepo"]
